name = "super"
version = "0.1.0"
description = "A Gleam project that depends on many other Gleam projects"
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.26"
nakai = "~> 0.8"
gleamy_structures = "~> 0.3"
gsv = "~> 0.1"
simplifile = "~> 0.1"
trie_again = "~> 1.1"
gliew = "~> 0.3"
glerm = "~> 0.1"
gleam_cors = "~> 0.2"
nibble = "~> 0.2"
globe = "~> 0.1"
glove = "~> 0.2"
glenvy = "~> 0.4"
glx = "~> 0.2"
ream = "~> 0.1"
non_empty_list = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 0.10"
