name: release-nightly

on:
  schedule:
    - cron: '45 0 * * *'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  nightly-last-run:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build-nightly-clean:
    runs-on: ubuntu-latest
    needs: [ nightly-last-run ]
    if: ${{ needs.nightly-last-run.outputs.should_run != 'false' }}
    steps:
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: nightly
          fail-if-no-assets: false
          fail-if-no-release: false
          assets: |
            *.zip
            *.tar.gz
            *.sha256
            *.sha512

  build-nightly:
    name: build-release
    runs-on: ${{ matrix.os }}
    needs: [ build-nightly-clean ]
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
        toolchain: [stable]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            use-cross: true
          - os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
          - os: macos-11
            target: aarch64-apple-darwin
            use-cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update versions
        shell: bash
        run: |
          version=0.0.0-nightly-$(date +"%y%m%d")
          
          sed "s/^version = \".*\"\$/version = \"$version\"/" compiler-core/Cargo.toml > /tmp/gleam-cargo.toml
          mv /tmp/gleam-cargo.toml compiler-core/Cargo.toml
          
          sed "s/^version = \".*\"\$/version = \"$version\"/" compiler-wasm/Cargo.toml > /tmp/gleam-cargo.toml
          mv /tmp/gleam-cargo.toml compiler-wasm/Cargo.toml
          
          sed "s/^version = \".*\"\$/version = \"$version\"/" compiler-cli/Cargo.toml > /tmp/gleam-cargo.toml
          mv /tmp/gleam-cargo.toml compiler-cli/Cargo.toml

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
          default: true
          profile: minimal

      - name: Handle Rust dependencies caching
        uses: Swatinem/rust-cache@v1
        with:
          key: v1-${{ matrix.target }}

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}

      - name: Build archive
        shell: bash
        run: |
          VERSION=nightly
          DAY=$(date +"%y%m%d")

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            ARCHIVE="gleam-$VERSION-${{ matrix.target }}.zip"
            cp "target/${{ matrix.target }}/release/gleam.exe" "gleam.exe"
            7z a "$ARCHIVE" "gleam.exe"
            rm gleam.exe
          else
            ARCHIVE="gleam-$VERSION-${{ matrix.target }}.tar.gz"
            cp "target/${{ matrix.target }}/release/gleam" "gleam"
            tar -czvf "$ARCHIVE" "gleam"
            rm gleam
          fi

          openssl dgst -r -sha256 -out "$ARCHIVE".sha256 "$ARCHIVE"
          openssl dgst -r -sha512 -out "$ARCHIVE".sha512 "$ARCHIVE"
          echo "ASSET=$ARCHIVE" >> $GITHUB_ENV
          echo "DAY=$DAY" >> $GITHUB_ENV

      - name: Ensure binary successfully boots
        shell: bash
        run: |
          case "${{ matrix.target }}" in
            x86_64-pc-windows-msvc)
              7z x "$ASSET"
              ./gleam.exe --version ;;
            aarch64*)
              echo "We cannot test an ARM binary on a AMD64 runner" ;;
            *)
              tar -xvzf "$ASSET"
              ./gleam --version ;;
          esac

      - name: Upload release archive
        shell: bash
        run: |
          for i in $(seq 5); do
            hub release edit nightly \
              --draft=false \
              --prerelease \
              --message=Nightly \
              --message="nightly release for ${{ env.DAY }}" \
              --attach="${{ env.ASSET }}" \
              --attach="${{ env.ASSET }}.sha256" \
              --attach="${{ env.ASSET }}.sha512" \
            && break
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUB_VERBOSE: 1
